// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import usecases "github.com/mastanca/SALES_MARTIN_STANCANELLI/usecases"

// GetSalesStatsPerCountry is an autogenerated mock type for the GetSalesStatsPerCountry type
type GetSalesStatsPerCountry struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx
func (_m *GetSalesStatsPerCountry) Execute(ctx context.Context) (usecases.StatsPerCountry, error) {
	ret := _m.Called(ctx)

	var r0 usecases.StatsPerCountry
	if rf, ok := ret.Get(0).(func(context.Context) usecases.StatsPerCountry); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(usecases.StatsPerCountry)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
