// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import ticket "github.com/mastanca/SALES_MARTIN_STANCANELLI/domain/ticket"

// RegisterTicketSale is an autogenerated mock type for the RegisterTicketSale type
type RegisterTicketSale struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, _a1
func (_m *RegisterTicketSale) Execute(ctx context.Context, _a1 ticket.Ticket) error {
	ret := _m.Called(ctx, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ticket.Ticket) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
