// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import gin "github.com/gin-gonic/gin"

import mock "github.com/stretchr/testify/mock"

// GetSaleStatsPerCountryHandler is an autogenerated mock type for the GetSaleStatsPerCountryHandler type
type GetSaleStatsPerCountryHandler struct {
	mock.Mock
}

// Handle provides a mock function with given fields: c
func (_m *GetSaleStatsPerCountryHandler) Handle(c *gin.Context) {
	_m.Called(c)
}
