// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import gin "github.com/gin-gonic/gin"

import mock "github.com/stretchr/testify/mock"

// RegisterTicketSaleHandler is an autogenerated mock type for the RegisterTicketSaleHandler type
type RegisterTicketSaleHandler struct {
	mock.Mock
}

// Handle provides a mock function with given fields: c
func (_m *RegisterTicketSaleHandler) Handle(c *gin.Context) {
	_m.Called(c)
}
